=== jmpzpg/LM/unidad_04/22-01-28/Ejercicios/_Ejercicio9DTD.dtd
<!ENTITY % t "(#PCDATA)" >
<!ELEMENT persona (nombre, nacimiento?, direccion+, varon)>
<!ELEMENT nombre %t;>
<!ELEMENT nacimiento EMPTY>
  <!ATTLIST nacimiento 
                  dia CDATA #IMPLIED
                  mes CDATA #IMPLIED
                  anyo CDATA #IMPLIED>
<!ELEMENT direccion (calle, poblacion, provincia, cpostal)>
<!ELEMENT calle %t;>
<!ELEMENT poblacion %t;>
<!ELEMENT provincia %t;>
<!ELEMENT cpostal %t;>
<!ELEMENT varon EMPTY>

=== jmpzpg/LM/unidad_04/22-01-28/Ejercicios/_Ejercicio9DTD.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE persona SYSTEM "_Ejercicio9DTD.dtd">
<persona>
  <nombre>Juan Pardo</nombre>
  <nacimiento dia="10" mes="Abril" anyo="1982"/>
  <direccion>
    <calle>Caoba,1</calle>
    <poblacion>Madrid</poblacion>
    <provincia>Madrid</provincia>
    <cpostal>28005</cpostal>  
  </direccion>
  <direccion>
    <calle>Alcalá,27</calle>
    <poblacion>Madrid</poblacion>
    <provincia>Madrid</provincia>
    <cpostal>28002</cpostal>
  </direccion>
  <varon/>
</persona>
